In [253]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [254]:
data = pd.read_csv('headbrain1.csv')

In [255]:
data.shape

(237, 4)

In [256]:
data.head()

Gender  Age Range  Head_Size  Brain_Weight
0       1          1       4512          1530
1       1          1       3738          1297
2       1          1       4261          1335
3       1          1       3777          1282
4       1          1       4177          1590

In [257]:
data.keys()

Index(['Gender', 'Age Range', 'Head_Size', 'Brain_Weight'], dtype='object')

In [258]:
data.Head_Size

0      4512
1      3738
2      4261
3      3777
4      4177
5      3585
6      3785
7      3559
8      3613
9      3982
10     3443
11     3993
12     3640
13     4208
14     3832
15     3876
16     3497
17     3466
18     3095
19     4424
20     3878
21     4046
22     3804
23     3710
24     4747
25     4423
26     4036
27     4022
28     3454
29     4175
       ... 
207    3995
208    3318
209    2720
210    2937
211    3580
212    2939
213    2989
214    3586
215    3156
216    3246
217    3170
218    3268
219    3389
220    3381
221    2864
222    3740
223    3479
224    3647
225    3716
226    3284
227    4204
228    3735
229    3218
230    3685
231    3704
232    3214
233    3394
234    3233
235    3352
236    3391
Name: Head_Size, Length: 237, dtype: int64

In [280]:
Y = data["Brain_Weight"].values.reshape(-1, 1)

In [281]:
Y

array([[1530],
       [1297],
       [1335],
       [1282],
       [1590],
       [1300],
       [1400],
       [1255],
       [1355],
       [1375],
       [1340],
       [1380],
       [1355],
       [1522],
       [1208],
       [1405],
       [1358],
       [1292],
       [1340],
       [1400],
       [1357],
       [1287],
       [1275],
       [1270],
       [1635],
       [1505],
       [1490],
       [1485],
       [1310],
       [1420],
       [1318],
       [1432],
       [1364],
       [1405],
       [1432],
       [1207],
       [1375],
       [1350],
       [1236],
       [1250],
       [1350],
       [1320],
       [1525],
       [1570],
       [1340],
       [1422],
       [1506],
       [1215],
       [1311],
       [1300],
       [1224],
       [1350],
       [1335],
       [1390],
       [1400],
       [1225],
       [1310],
       [1560],
       [1330],
       [1222],
       [1415],
       [1175],
       [1330],
       [1485],
       [1470],
       [1135],
       [13

In [282]:
X = data["Head_Size"].values.reshape(-1, 1)

In [283]:
X

array([[4512],
       [3738],
       [4261],
       [3777],
       [4177],
       [3585],
       [3785],
       [3559],
       [3613],
       [3982],
       [3443],
       [3993],
       [3640],
       [4208],
       [3832],
       [3876],
       [3497],
       [3466],
       [3095],
       [4424],
       [3878],
       [4046],
       [3804],
       [3710],
       [4747],
       [4423],
       [4036],
       [4022],
       [3454],
       [4175],
       [3787],
       [3796],
       [4103],
       [4161],
       [4158],
       [3814],
       [3527],
       [3748],
       [3334],
       [3492],
       [3962],
       [3505],
       [4315],
       [3804],
       [3863],
       [4034],
       [4308],
       [3165],
       [3641],
       [3644],
       [3891],
       [3793],
       [4270],
       [4063],
       [4012],
       [3458],
       [3890],
       [4166],
       [3935],
       [3669],
       [3866],
       [3393],
       [4442],
       [4253],
       [3727],
       [3329],
       [34

In [304]:
x_mean = np.mean(x_test)

In [294]:
x_mean

3633.9915611814345

In [305]:
y_mean = np.mean(y_test)

In [306]:
y_mean

1290.2291666666667

In [244]:
print(data.describe())

           Gender   Age Range    Head_Size  Brain_Weight
count  237.000000  237.000000   237.000000    237.000000
mean     1.434599    1.535865  3633.991561   1282.873418
std      0.496753    0.499768   365.261422    120.340446
min      1.000000    1.000000  2720.000000    955.000000
25%      1.000000    1.000000  3389.000000   1207.000000
50%      1.000000    2.000000  3614.000000   1280.000000
75%      2.000000    2.000000  3876.000000   1350.000000
max      2.000000    2.000000  4747.000000   1635.000000


In [284]:
x, y = X, Y

In [285]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [286]:
regressor = LinearRegression()

In [287]:
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [288]:
pred = regressor.predict(x_test)

In [289]:
pred[0]

array([1306.48231242])

In [290]:
y_test[0]

array([1280], dtype=int64)

In [291]:
print(x_test.size)

48


In [292]:
print(x.size)

237


In [301]:
rss = sum((y_test - pred)**2)

In [302]:
rss

array([249629.5423675])

In [307]:
tss = sum((y_test -y_mean)**2)

In [308]:
tss

array([688892.47916667])

In [309]:
r2_score = 1 - (rss / tss)

In [310]:
r2_score

array([0.63763642])